export default {
  LOAD: 'LOAD',
  INIT: 'INIT',
  CLEAR: 'CLEAR',
  ADD: 'ADD',
  CHANGE: 'CHANGE',
  REMOVE: 'REMOVE',
  READY_EDIT: 'READY_EDIT',
  LOCAL_EDIT: 'LOCAL_EDIT',
  COMMIT_EDIT: 'COMMIT_EDIT',
  CANCEL_EDIT: 'CANCEL_EDIT',

  CHANGE_MODE: 'CHANGE_MODE',
  ADD_NODE: 'ADD_NODE',
  REMOVE_NODE: 'REMOVE_NODE',
  SELECT_NODE: 'SELECT_NODE',
  LOCAL_MOVE_NODE: 'LOCAL_MOVE_NODE',
  UPDATE_NODE: 'UPDATE_NODE',

  MOVE_VIEW: 'MOVE_VIEW',

  CURSOR_DOWN: 'CURSOR_DOWN',
  CURSOR_DOWN_ON_NODE: 'CURSOR_DOWN_ON_NODE',
  CURSOR_DRAG: 'CURSOR_DRAG',
  CURSOR_UP: 'CURSOR_UP',
  WHEEL_ON_CANVAS: 'WHEEL_ON_CANVAS'
}
