export default {
  LOAD: 'LOAD',
  CLEAR: 'CLEAR',
  ADD: 'ADD',
  CHANGE: 'CHANGE',
  REMOVE: 'REMOVE',
  READY_EDIT: 'READY_EDIT',
  LOCAL_EDIT: 'LOCAL_EDIT',
  COMMIT_EDIT: 'COMMIT_EDIT',
  CANCEL_EDIT: 'CANCEL_EDIT'
}
